// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module '*.css';

// filepath: src/images.d.ts
declare module '*.png' {
  const value: string;
  export default value;
}
